# ----------------------------------
# Nginx
# Use to serve the request of all services

nginx:
    image: jwilder/nginx-proxy:latest
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
    ports:
        - "80:80"
    restart: always

# ----------------------------------
# Blog jonglage
# A blog on jonglage

web-jonglage:
    image: nginx
    links:
        - blog-jonglage
    volumes:
        - ./web-jonglage/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./web-jonglage/vhost.d:/etc/nginx/vhost.d
    volumes_from:
        - server_data-jonglage-static_1
    environment:
        - VIRTUAL_HOST=jonglage.localdomain
        - VIRTUAL_PORT=80
    restart: always

data-jonglage:
    image: ubuntu:latest
    volumes:
        - /var/lib/mysql

blog-jonglage:
    build: ./blog-jonglage/
    ports:
        - "80"
    links:
        - database-jonglage
    volumes_from:
        - data-jonglage-static
    restart: always
    command: /app/blog-jonglage/./start.sh

database-jonglage:
    image: mariadb:latest
    volumes_from:
        - data-jonglage
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: pierrick
        MYSQL_PASSWORD: pierrickpass
        MYSQL_DATABASE: jonglage
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --character-set-client-handshake=FALSE
    restart: always

data-jonglage-static:
    image: ubuntu:latest
    volumes:
        - /data

# ----------------------------------
# Shaarli
# Microblogging service

shaarli:
    image: crichon/shaarli
    ports:
        - "80"
    environment:
        VIRTUAL_HOST: shaarli.localdomain
    volumes_from:
        - shaarlidata
    restart: always

shaarlidata:
    image: ubuntu:latest
    volumes:
        - /var/www/html/data
    command: "echo shaarli data container"

# -----------------------------------------------
# Etherpad
# Collaborative text document writing

mysqlData:
    image: ubuntu:latest
    volumes:
        - /var/lib/mysql

db:
    image: mysql:5.7
    volumes_from:
        - mysqlData
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: dev
        MYSQL_PASSWORD: devpassword
        MYSQL_DATABASE: etherpad
    restart: always

etherpad:
    build: ./etherpad-pierrick/
    links:
        - db
    command: /opt/etherpad/bin/./run.sh
    ports:
        - "80"
    environment:
        VIRTUAL_HOST: pads.localdomain
    restart: always

# -------------------------------------------------------------
# wallabag
# Self hostable application to save web page

wallabagdata:
    image: ubuntu:latest
    volumes:
        - /var/www/wallabag/data

wallabag:
    image: wallabag/wallabag
    ports:
        - "80"
    environment:
        VIRTUAL_HOST: bag.localdomain
        SYMFONY__ENV__DOMAIN_NAME: http://bag.localdomain
    volumes_from:
        - wallabagdata
    restart: always

# -----------------------------------------------
# ep-project
# Project made to show my skills to the EP-startup
# See here: https://github.com/bwatt-fr/ep-project
ep-project:
    build: ./ep-project/
    ports:
        - "80"
    environment:
        VIRTUAL_HOST: ep-project.localdomain
    command: /app/ep-project/./start.sh
    restart: always

# -----------------------------------------------
house-monitoring:
    build: ./house-monitoring/
    ports:
        - "8000"
        - "8001:8001"
    environment:
        VIRTUAL_HOST: on-se-capte-a-la-maison.localdomain
        VIRTUAL_PORT: 8000
    volumes_from:
        - house-monitoring-data
    command: bash -c "cp -n /app/house-monitoring.db /data && /app/webserver -c /app/conf.json"
    restart: always

house-monitoring-data:
    image: ubuntu:latest
    volumes:
        - /data

# -----------------------------------------------
nextcloud-web:
    image: nginx
    links:
      - nextcloud-app
    volumes:
        - ./nextcloud-web/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloud-app
    environment:
      - VIRTUAL_HOST=nextcloud.localdomain
      - VIRTUAL_PORT=80
    restart: always

nextcloud-app:
    image: nextcloud:fpm
    links:
      - nextcloud-db
    volumes:
      - /var/www/html/apps
      - /var/www/html/config
      - /var/www/html/data
    restart: always
    
nextcloud-db:
    image: mariadb
    volumes_from:
      - nextcloud-data
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    restart: always

nextcloud-data:
    image: ubuntu:latest
    volumes:
        - /var/lib/mysql
