# traefik.toml
################################################################
# Global configuration
################################################################

defaultEntryPoints = ["http"]


[entryPoints]
  [entryPoints.http]
  address = ":80"

[web]
address = ":8080" # Traefik web interface

[docker]
endpoint = "unix:///var/run/docker.sock" # Socket unix or TCP possible 
domain = "localdomain" # Default domain
watch = true # Traefik will know when there will be changes on Docker

exposedbydefault = true 

[http]
  [middlewares]
    [SecHeaders]
      [headers]
        frameDeny = true
	contentTypeNosniff = true
	browserXssFilter = true
	forceSTSHeader = true
	stsIncludeDubdomains = true
	stsSeconds = 31536000

[tls]
  [options]
    [default]
      minVersion = "VersionTLS12"
      sniStrict = true
